all: check build embedded clippy check-fmt docs

clippy:
  cargo clippy -- -D warnings

fmt:
  cargo fmt --all

check-fmt:
  cargo fmt --all -- --check

check:
  cargo check

embedded:
  cargo build --target armv7a-none-eabihf

build:
  cargo build

docs:
  RUSTDOCFLAGS="--cfg docsrs -Z unstable-options --generate-link-to-definition" cargo +nightly doc --no-deps

docs-html:
  RUSTDOCFLAGS="--cfg docsrs -Z unstable-options --generate-link-to-definition" cargo +nightly doc --open --no-deps
