# .gitlab-ci.yml

image: rust:latest

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

stages:
  - stage1
  - stage2

.common_setup:
  cache:
    paths: 
      - .cargo/registry
      - .cargo/git
      - .cargo/bin
      - axi-uart16550/target/
      - axi-uartlite/target/
    key: ${CI_COMMIT_REF_SLUG}

.rust_setup_cross_compilation:
  extends: .common_setup
  before_script:
    - rustup target add armv7-unknown-linux-gnueabihf
    - rustup target add armv7a-none-eabihf

include:
  - local: '.gitlab/ci/axi-uartlite.yml'
  - local: '.gitlab/ci/axi-uart16550.yml'
