all: check build embedded clippy check-fmt docs

clippy:
  cargo clippy -- -D warnings

fmt:
  cargo fmt --all

check-fmt:
  cargo fmt --all -- --check

check:
  cargo check

embedded:
  cargo build --target armv7a-none-eabihf

test:
  cargo nextest r
  cargo test --doc

build:
  cargo build
  cargo build --features portable-atomic

docs:
  RUSTDOCFLAGS="--cfg docsrs -Z unstable-options --generate-link-to-definition" cargo +nightly doc --no-deps

docs-html:
  RUSTDOCFLAGS="--cfg docsrs -Z unstable-options --generate-link-to-definition" cargo +nightly doc --open --no-deps

coverage:
  cargo llvm-cov nextest

coverage-html:
  cargo llvm-cov nextest --html --open
